version:  '3.7'

services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql:/var/lib/mysql
            - ./backups:/backups

    maria:
        image: mariadb:10.4
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./maria:/var/lib/mysql
            - ./backups:/backups
